services:
  receiver:
    image: pyrtc_image:latest
    privileged: true
    volumes:
      - ./share:/app/share
    container_name: rtc_c2
    user: "user"
    command: python run.py -A "dummy"
    networks:
      rtcnet:
        ipv4_address: 192.168.2.102
  
  sender:
    image: pyrtc_image:latest
    privileged: true
    volumes:
      - ./share:/app/share
    container_name: rtc_c1
    depends_on:
      - receiver
    user: "user"
    environment:
      ARG_A: "dummy"
    command: ["/bin/bash", "entrypoint_sender.sh"]
    networks:
      rtcnet:
        ipv4_address: 192.168.2.101

networks:
  rtcnet:
    external: true
